### ISSUE TITLE
ULS23 Challenge Public Training Dataset problem

### ISSUE THREAD

**Issue by junqiangchen** [MJJdG/ULS23#1]
Hi,
thank you for sharing the ULS23 dataset,but i am confused about the dataset.just like this picture,i find the .z01,.z02,...,z10 and .zip file have same image files,which file should be using? 
![image](https://github.com/MJJdG/ULS23/assets/28638716/ef2aaaa8-6e44-4e47-915d-c1ee2a98cf98)
thank you!!
chenjunqiang

**Comment by MJJdG** [comment]
Hi junqiangchen,

The image data is part-zipped, meaning you should download all the separate zip files, place them in the same location and then extract the main `ULS23_PartX.zip` file. Please let me know if this solves your issue.

Kind regards,

Max

**Comment by junqiangchen** [comment]
@MJJdG thank you,i will download all dataset.

**Comment by ashishch-git** [comment]
I downloaded all zip files for Part 6 and tried to unzip the main file, "ULS23_Part6.zip". After that I tried to unzip "ULS23\processed_data\partially_annotated\DeepLesion\images.zip," but it didn't work as expected. I am not sure if there is some issue with the zip files (maybe some parts are missing or not named correctly). Please find the attached screenshots of the image folder. With the file structure in the screenshot, it was showing "images.z01 missing" so I tried to rename files from "images.z21" to "images.z01" but still received errors like "images.z08 missing" and header information missing. 

Please let me know if you know how to fix this issue.

![image](https://github.com/MJJdG/ULS23/assets/20603343/b3a203f8-27a7-4fb5-9dbe-94df763b7ab2)

![image](https://github.com/MJJdG/ULS23/assets/20603343/04ecc417-5045-4be3-9069-5a777b412d64)

**Comment by ashishch-git** [comment]
Also, if you have a better way, please guide us on extracting these files on your preferred OS (Linux or Windows).

**Comment by so-sal** [comment]
I could extract all the data correctly, using the command "7z x ULS23_Part1.zip" in ubuntu bash shell.
