### ISSUE TITLE
About the Part 1: Novel annotated data

### ISSUE THREAD

**Issue by Yuxin-Du-Lab** [MJJdG/ULS23#2]
You've done some really promising work!😁

I'm curious, have the 3D labels of **Part 1: Novel annotated data** not been released yet? I cannot find the label dir in the Part 1  zip file.

Thank you for your time.

**Comment by MJJdG** [comment]
Hi Yuxin,

You can find the 3D labels [on this repo](https://github.com/MJJdG/ULS23/tree/main/annotations/ULS23), you can merge it with the imaging data folders from Zenodo. We opted to keep the annotations separate so we can more easily track problems with individual lesion masks and update them were possible.

**Comment by Yuxin-Du-Lab** [comment]
Thank you a lot! Really amazing work. 🥰
