### ISSUE TITLE
Images and annotations do not match

### ISSUE THREAD

**Issue by baifanxxx** [MJJdG/ULS23#4]
Hi,

Thank you for your contribution. I loaded the ULS23_DeepLesion3D subset from your link. I found 750 images but 743 masks. In ULS23_Radboudumc_Bone, I also found 744 images but 697 masks. This means that the images and annotations do not match. Is it right? Or do I have something wrong? 

Best regards,
BAI Fan

**Comment by MJJdG** [comment]
Hi BAI Fan,

You are correct that there are fewer masks than images in those cases. We removed/improved a number of incorrect training cases in [this commit](https://github.com/MJJdG/ULS23/commit/b41cbcc612a273b1022222a98fd7531d046524b6). You can discard the images that do not have a mask associated with them. At a later date, we will reorganize the image data on Zenodo and remove these cases.

**Comment by baifanxxx** [comment]
Thank you for getting back to me. Your dataset is very helpful.
